import type { Metadata } from "next";
import { Bricolage_Grotesque } from "next/font/google";
import "./globals.css"; 
import Nav from "@/components/common/nav";
import Footer from "@/components/sections/footer";

const bricolageGrotesque = Bricolage_Grotesque({
  variable: "--font-bricolage-grotesque",
  subsets: ["latin"],
});

 

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html
      lang="en"
      className={`${bricolageGrotesque.variable}  h-full antialiased`}
    >
      <body className="min-h-full flex flex-col"> 
        <Nav/>
        {children} 
        <Footer/>
      </body>
    </html>
  );
}
